---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Outputs:
  DistributionId:
    Value: !Ref CloudFrontDistribution
  AppUrl:
    Value: !GetAtt CloudFrontDistribution.DomainName
  ApiUrl:
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/

Resources:
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: wapp-example

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'CloudFront OAI'

  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Join ['/', [!GetAtt WebBucket.Arn, '*']]
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: s3:ListBucket
            Resource: !GetAtt WebBucket.Arn

  HttpApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      MemorySize: 128
      Timeout: 30
      Handler: ./main
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Method: ANY
            Path: '$default'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: http2
        Enabled: true
        IPV6Enabled: true
        PriceClass: PriceClass_All
        Origins:
          - Id: s3
            DomainName: !GetAtt WebBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
          - Id: app
            DomainName: !Sub ${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: app
          AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
          ViewerProtocolPolicy: https-only
          Compress: true
          ForwardedValues:
            QueryString: true
        CacheBehaviors:
          - TargetOriginId: s3
            PathPattern: /assets/*
            AllowedMethods: [HEAD, GET]
            CachedMethods: [HEAD, GET]
            ViewerProtocolPolicy: https-only
            Compress: true
            ForwardedValues:
              QueryString: false
