apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: development-
namespace: development-my-app
commonLabels:
  environment: development

bases:
  - ../../base

resources:
  - namespace.yaml

images:
  - name: example
    newName: example
    newTag: latest

secretGenerator:
  - name: my-app
    namespace: development-my-app
    literals:
      - NAMESPACE=development
      - POSTGRES_PASSWORD=password
      - POSTGRES_REPLICATION_PASSWORD=password
      - DATABASE_URL=postgres://postgres:password@development-kubegres:5432/postgres?sslmode=disable
