apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: example-dbmate:develop
          command: ["dbmate", "up"]
          envFrom:
            - secretRef:
                name: development-my-app