apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: my-app
          image: example-app:develop
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: my-app