apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: kubegres
spec:
  replicas: 3
  image: postgres:14.1
  database:
    size: 1Gi
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-app
          key: POSTGRES_PASSWORD

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-app
          key: POSTGRES_REPLICATION_PASSWORD
