apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: development-
namespace: development-my-app
commonLabels:
  environment: development

bases:
  - ../base

resources:
  - namespace.yaml

patchesStrategicMerge:
  - configmap.yaml