apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: production-
namespace: production-my-app
commonLabels:
  environment: production

bases:
  - ../base

resources:
  - namespace.yaml

patchesStrategicMerge:
  - configmap.yaml